spring.application.name=BackendCRUD2
spring.datasource.url=${mysql_env:jdbc:mysql://localhost:3306/MiniSaes}
spring.datasource.username=${mysql_env:root}
spring.datasource.password=${mysql_env:Saulivan1$}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect